export default {
  ADD_SECTION: "ADD_SECTION",
  DELETE_SECTION: "DELETE_SECTION",
  ADD_FILD: "ADD_FIELD",
  DELETE_FIELD: "DELETE_FIELD",
  UPDATE_SECTION: "UPDATE_SECTION",
  UPDATE_FIELD: "UPDAT_FILD",
};
